import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Box from '@mui/material/Box';

import Typography from '@mui/material/Typography';



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "QRcode Buffet Order",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Box sx={{ bgcolor: '#12372A', color: '#FBFADA', p: 3 }}>
          <Typography variant="h3" component="div" textAlign='center'>
            อร่อยบอกต่อ ไม่อร่อยก็กินให้หมด
          </Typography>

      </Box>

          {children}
      
        
      </body>
    </html>
  );
}
